theme: jekyll-theme-minimal
#
# This file contains configuration flags to customize your site
#
title: Lilian Berton
# Name of your site (displayed in the header)
name: Your Name

# Short bio or description (displayed in the header)
#description: blabla 

# URL of your avatar or profile pic (you could use your GitHub profile pic)
logo: https://avatars3.githubusercontent.com/u/13876182?s=460&v=4
