theme: jekyll-theme-minimal
url: "http://lberton.github.io"
baseurl: ""
title: Lilian Bertonn
# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: "https://avatars3.githubusercontent.com/u/13876182?s=460&v=4"
title-img: https://avatars3.githubusercontent.com/u/13876182?s=460&v=4

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
    - GitHub Pages: "https://pages.github.com/"
  Author's home: "http://deanattali.com"
